/* ===========================================================
   TickeMate AI — data + translations (EN / JA / ZH / KO)
   Default language: KO. Exposed on window.
   =========================================================== */

const CONCERTS = [
  {
    id: "aurora",
    artist: "AURORA NOVA",
    tour: "WORLD TOUR : SUPERNOVA",
    venue: { en: "Gocheok Sky Dome, Seoul", ja: "高尺スカイドーム, ソウル", zh: "高尺天空巨蛋, 首尔", ko: "고척스카이돔, 서울" },
    date: "2026.08.22",
    day: { en: "Sat", ja: "土", zh: "六", ko: "토" },
    time: "18:00",
    hot: true,
    gradient: "linear-gradient(135deg,#3f74e0,#b56cff)",
    priceFrom: 132000,
  },
  {
    id: "luna8",
    artist: "LUNA8",
    tour: "FAN CONCERT : MOONLIGHT",
    venue: { en: "KSPO Dome, Seoul", ja: "KSPOドーム, ソウル", zh: "KSPO巨蛋, 首尔", ko: "KSPO돔, 서울" },
    date: "2026.09.05",
    day: { en: "Sat", ja: "土", zh: "六", ko: "토" },
    time: "19:00",
    hot: true,
    gradient: "linear-gradient(135deg,#6ea8ff,#4fd6c0)",
    priceFrom: 121000,
  },
  {
    id: "stellar",
    artist: "STELLAR",
    tour: "THE SHOW : ENCORE",
    venue: { en: "Inspire Arena, Incheon", ja: "インスパイア・アリーナ, 仁川", zh: "Inspire 竞技场, 仁川", ko: "인스파이어 아레나, 인천" },
    date: "2026.09.19",
    day: { en: "Sat", ja: "土", zh: "六", ko: "토" },
    time: "18:30",
    hot: false,
    gradient: "linear-gradient(135deg,#ff6f9c,#ffce6e)",
    priceFrom: 110000,
  },
  {
    id: "vivid",
    artist: "VIVID",
    tour: "1ST CONCERT : PROLOGUE",
    venue: { en: "Jamsil Indoor Stadium, Seoul", ja: "蚕室室内体育館, ソウル", zh: "蚕室室内体育馆, 首尔", ko: "잠실실내체육관, 서울" },
    date: "2026.10.03",
    day: { en: "Sat", ja: "土", zh: "六", ko: "토" },
    time: "17:00",
    hot: false,
    gradient: "linear-gradient(135deg,#8a6cff,#6ea8ff)",
    priceFrom: 99000,
  },
];

/* Seat tiers + a generated grid for the seat map */
const SEAT_TIERS = [
  { id: "vip", labelKey: "tierVip", color: "#ff6f9c", price: 187000 },
  { id: "r", labelKey: "tierR", color: "#6ea8ff", price: 154000 },
  { id: "s", labelKey: "tierS", color: "#4fd6c0", price: 132000 },
];

const T = {
  en: {
    code: "EN",
    appTag: "AI ticketing co-pilot",
    aiName: "Mate",
    aiStatus: "online · guiding you",
    next: "Continue",
    back: "Back",
    confirm: "Confirm",
    step: "Step",
    of: "of",

    // intro
    introEyebrow: "Welcome to TickeMate AI",
    introTitle: "Never lose a ticket war again.",
    introSub: "I'm Mate — your AI co-pilot. I'll walk you through every step of the booking, from fan-club presale to checkout, so you can grab the seat you want without the panic.",
    introBullet1: "Real-time queue strategy",
    introBullet2: "Auto-filled forms & verification",
    introBullet3: "Smart seat recommendations",
    introCta: "Start booking",
    introNote: "Demo · no real payment is processed",

    // step labels
    s1: "Concert", s2: "Account", s3: "Fan Club", s4: "Queue", s5: "Seats", s6: "Payment",

    // step 1
    s1Eyebrow: "Step 1 — Choose your show",
    s1Title: "Which concert are we winning today?",
    s1Sub: "Pick the show you're after. I'll prep everything for that specific sale.",
    s1Ai: "Let's start with the show. Tap the concert you want — I'll line up the right presale and timing for it.",
    hot: "HOT",
    from: "from",
    select: "Select",
    selected: "Selected",

    // step 2
    s2Eyebrow: "Step 2 — Account",
    s2Title: "Let's get your account ready",
    s2Sub: "You'll need a verified account before the sale opens. I'll auto-fill what I can.",
    s2Ai: "Most ticket wars are lost at login. Let's set up a verified account now so you're ready the second the sale opens.",
    s2a: "Email", s2aSub: "We'll send a verification code here",
    s2b: "Verify", s2bSub: "Enter the 6-digit code we sent",
    s2c: "Password", s2cSub: "Make it strong — you'll move fast on sale day",
    s2d: "Profile", s2dSub: "Real name as on your ID (required to enter)",
    s2e: "Phone", s2eSub: "For sale-day alerts & identity check",
    emailPh: "you@email.com",
    codePh: "0 0 0 0 0 0",
    pwPh: "8+ characters",
    namePh: "Full name",
    phonePh: "+82 10-0000-0000",
    resend: "Resend code",
    autofill: "Mate auto-filled this",
    verified: "Verified",
    accountReady: "Account verified & ready",

    // step 3
    s3Eyebrow: "Step 3 — Fan Club",
    s3Title: "Join the fan club for presale access",
    s3Sub: "Members get into the presale 48h early — that's where the best seats go.",
    s3Ai: "Here's the secret: the best seats sell in presale. Joining the official fan club unlocks it. I recommend the membership below.",
    s3Benefit1: "48-hour early presale access",
    s3Benefit2: "Dedicated members-only seat block",
    s3Benefit3: "Lower queue numbers on average",
    s3Benefit4: "Exclusive membership card & perks",
    membership: "OFFICIAL MEMBERSHIP",
    perYear: "/ year",
    joinNow: "Join & unlock presale",
    joined: "Membership active",
    memberNo: "Member No.",

    // step 4
    s4Eyebrow: "Step 4 — Waiting Room",
    s4Title: "You're in the queue",
    s4Sub: "Stay on this page. Refreshing or leaving will send you to the back.",
    s4Ai: "The sale is live and you're in the queue. Do NOT refresh — I'll hold your place and tell you the moment it's your turn.",
    queuePosition: "Your position",
    peopleAhead: "people ahead of you",
    estWait: "Estimated wait",
    queueTip: "Mate is holding your spot — sit tight.",
    yourTurn: "It's your turn!",
    yourTurnSub: "You're in. Let's grab those seats — fast.",
    enterSeats: "Choose seats now",
    min: "min", sec: "sec",

    // step 5
    s5Eyebrow: "Step 5 — Seat selection",
    s5Title: "Pick your seats",
    s5Sub: "Tap an available seat. I've highlighted the best value with a great view.",
    s5Ai: "We're in! I've scanned the map — the seats glowing blue are the best balance of price and view. Grab them before they go.",
    stage: "STAGE",
    available: "Available",
    taken: "Taken",
    yourPick: "Your pick",
    recommend: "Mate's pick",
    seatsSelected: "seats selected",
    selectSeatsHint: "Select up to 2 seats",
    seatSummary: "Selected seats",
    subtotal: "Subtotal",
    toPayment: "Go to payment",

    // step 6
    s6Eyebrow: "Step 6 — Payment",
    s6Title: "Last step — checkout",
    s6Sub: "Your seats are held for 7:00. Complete payment to lock them in.",
    s6Ai: "Seats are reserved but only for 7 minutes. Let's finish payment before the timer runs out — I've pre-filled your details.",
    held: "Seats held",
    orderSummary: "Order summary",
    bookingFee: "Booking fee",
    total: "Total",
    payMethod: "Payment method",
    card: "Card", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "Card number", cardPh: "1234 5678 9012 3456",
    expiry: "Expiry", expPh: "MM/YY", cvc: "CVC", cvcPh: "•••",
    agree: "I agree to the ticketing terms & no-refund policy",
    payNow: "Pay",
    processing: "Securing your seats…",

    // completion
    doneEyebrow: "Booking confirmed",
    doneTitle: "You got the tickets! 🎉",
    doneSub: "Mate guided you through 6 steps in record time. Your e-tickets are ready.",
    doneAi: "We did it! Tickets secured. I've sent the e-tickets to your email and added the show to your calendar. Enjoy the concert!",
    bookingNo: "Booking number",
    eTicket: "E-TICKET",
    seatLabel: "Seat",
    addCalendar: "Add to calendar",
    viewTickets: "View e-tickets",
    bookAnother: "Book another show",
    timeTaken: "Total time with Mate",
    admitOne: "ADMIT",
  },

  ja: {
    code: "JA",
    appTag: "AIチケッティング・コパイロット",
    aiName: "メイト",
    aiStatus: "オンライン · ガイド中",
    next: "次へ", back: "戻る", confirm: "確認", step: "ステップ", of: "/",
    introEyebrow: "TickeMate AI へようこそ",
    introTitle: "もうチケット戦争で負けない。",
    introSub: "私はメイト、あなたのAIコパイロット。ファンクラブ先行から決済まで、予約の全ステップをご案内します。",
    introBullet1: "リアルタイム待機列の戦略", introBullet2: "自動入力と本人確認", introBullet3: "スマートな座席提案",
    introCta: "予約を始める", introNote: "デモ · 実際の決済は行われません",
    s1: "コンサート", s2: "アカウント", s3: "ファンクラブ", s4: "待機列", s5: "座席", s6: "決済",
    s1Eyebrow: "ステップ1 — 公演を選ぶ", s1Title: "今日はどの公演を取りに行く？", s1Sub: "狙う公演を選んでください。それに合わせて準備します。",
    s1Ai: "まずは公演から。欲しいコンサートをタップしてください。先行と時間を合わせて準備します。",
    hot: "人気", from: "より", select: "選択", selected: "選択済み",
    s2Eyebrow: "ステップ2 — アカウント", s2Title: "アカウントを準備しましょう", s2Sub: "販売前に本人確認済みのアカウントが必要です。",
    s2Ai: "チケット戦争はログインで負けがち。今のうちに認証済みアカウントを準備しましょう。",
    s2a: "メール", s2aSub: "ここに認証コードを送ります", s2b: "認証", s2bSub: "6桁のコードを入力", s2c: "パスワード", s2cSub: "強力に — 販売日は素早く",
    s2d: "プロフィール", s2dSub: "本人確認書類どおりの氏名", s2e: "電話", s2eSub: "販売日通知と本人確認用",
    emailPh: "you@email.com", codePh: "0 0 0 0 0 0", pwPh: "8文字以上", namePh: "氏名", phonePh: "090-0000-0000",
    resend: "コード再送", autofill: "メイトが自動入力", verified: "認証済み", accountReady: "アカウント認証完了",
    s3Eyebrow: "ステップ3 — ファンクラブ", s3Title: "先行のためファンクラブに加入", s3Sub: "会員は48時間早く先行に入れます。",
    s3Ai: "秘訣は先行販売。公式ファンクラブで解錠できます。下の会員をおすすめします。",
    s3Benefit1: "48時間前の先行アクセス", s3Benefit2: "会員専用の座席ブロック", s3Benefit3: "平均的に低い待機番号", s3Benefit4: "限定会員カードと特典",
    membership: "公式会員", perYear: "/ 年", joinNow: "加入して先行を解錠", joined: "会員有効", memberNo: "会員番号",
    s4Eyebrow: "ステップ4 — 待機室", s4Title: "待機列に入りました", s4Sub: "このページのままで。更新や離脱は最後尾へ。",
    s4Ai: "販売開始、待機列にいます。更新は絶対しないで — 順番が来たら知らせます。",
    queuePosition: "あなたの順番", peopleAhead: "人があなたの前に", estWait: "推定待ち時間", queueTip: "メイトが順番をキープ中。",
    yourTurn: "あなたの番です！", yourTurnSub: "入れました。座席を素早く確保！", enterSeats: "今すぐ座席を選ぶ", min: "分", sec: "秒",
    s5Eyebrow: "ステップ5 — 座席選択", s5Title: "座席を選ぶ", s5Sub: "空席をタップ。お得で見やすい席を強調しました。",
    s5Ai: "入れました！マップを分析 — 青く光る席が価格と視界のベストバランスです。",
    stage: "ステージ", available: "空席", taken: "売切", yourPick: "あなたの選択", recommend: "メイト推薦",
    seatsSelected: "席選択中", selectSeatsHint: "最大2席まで", seatSummary: "選択した座席", subtotal: "小計", toPayment: "決済へ",
    s6Eyebrow: "ステップ6 — 決済", s6Title: "最終ステップ — 決済", s6Sub: "座席は7:00間キープ中。決済で確定します。",
    s6Ai: "座席は7分間だけ確保。タイマー前に決済を終えましょう。情報は入力済みです。",
    held: "座席キープ中", orderSummary: "注文内容", bookingFee: "予約手数料", total: "合計",
    payMethod: "支払い方法", card: "カード", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "カード番号", cardPh: "1234 5678 9012 3456", expiry: "有効期限", expPh: "MM/YY", cvc: "CVC", cvcPh: "•••",
    agree: "チケット規約と返金不可に同意します", payNow: "支払う", processing: "座席を確保中…",
    doneEyebrow: "予約確定", doneTitle: "チケット獲得！🎉", doneSub: "メイトと6ステップを最速で。e-チケット準備完了。",
    doneAi: "やりました！チケット確保。e-チケットをメール送信し、カレンダーにも追加しました。",
    bookingNo: "予約番号", eTicket: "e-チケット", seatLabel: "座席", addCalendar: "カレンダーに追加",
    viewTickets: "e-チケットを見る", bookAnother: "別の公演を予約", timeTaken: "メイトとの合計時間", admitOne: "入場",
  },

  zh: {
    code: "ZH",
    appTag: "AI 抢票副驾驶",
    aiName: "小队",
    aiStatus: "在线 · 引导中",
    next: "继续", back: "返回", confirm: "确认", step: "步骤", of: "/",
    introEyebrow: "欢迎使用 TickeMate AI",
    introTitle: "再也不会抢票失败。",
    introSub: "我是小队，你的 AI 副驾驶。从粉丝会预售到结账，我会带你走完每一步。",
    introBullet1: "实时排队策略", introBullet2: "自动填表与验证", introBullet3: "智能座位推荐",
    introCta: "开始购票", introNote: "演示 · 不会进行真实付款",
    s1: "演唱会", s2: "账户", s3: "粉丝会", s4: "排队", s5: "座位", s6: "付款",
    s1Eyebrow: "第 1 步 — 选择演出", s1Title: "今天我们要抢哪场？", s1Sub: "选择目标演出，我会为它做好准备。",
    s1Ai: "先从演出开始。点击你想要的演唱会，我会安排对应的预售和时间。",
    hot: "热门", from: "起", select: "选择", selected: "已选择",
    s2Eyebrow: "第 2 步 — 账户", s2Title: "准备好你的账户", s2Sub: "开售前需要已验证的账户,我会尽量自动填写。",
    s2Ai: "抢票常常输在登录。现在就设置好验证账户,开售即可就绪。",
    s2a: "邮箱", s2aSub: "验证码将发送到这里", s2b: "验证", s2bSub: "输入 6 位验证码", s2c: "密码", s2cSub: "设强一点 — 开售要快",
    s2d: "资料", s2dSub: "与证件一致的真实姓名", s2e: "手机", s2eSub: "用于开售提醒与身份核验",
    emailPh: "you@email.com", codePh: "0 0 0 0 0 0", pwPh: "8 位以上", namePh: "姓名", phonePh: "+86 100 0000 0000",
    resend: "重新发送", autofill: "小队已自动填写", verified: "已验证", accountReady: "账户已验证就绪",
    s3Eyebrow: "第 3 步 — 粉丝会", s3Title: "加入粉丝会获取预售", s3Sub: "会员可提前 48 小时进入预售。",
    s3Ai: "秘诀:最好的座位在预售。加入官方粉丝会即可解锁,我推荐下面的会员。",
    s3Benefit1: "提前 48 小时预售", s3Benefit2: "会员专属座位区", s3Benefit3: "平均更靠前的排队号", s3Benefit4: "专属会员卡与福利",
    membership: "官方会员", perYear: "/ 年", joinNow: "加入并解锁预售", joined: "会员有效", memberNo: "会员号",
    s4Eyebrow: "第 4 步 — 等候室", s4Title: "你已进入排队", s4Sub: "请停留本页,刷新或离开会被排到最后。",
    s4Ai: "开售了,你在排队中。千万别刷新 — 我帮你守住位置,轮到你会通知你。",
    queuePosition: "你的位置", peopleAhead: "人排在你前面", estWait: "预计等待", queueTip: "小队正在为你守位,稍候。",
    yourTurn: "轮到你了!", yourTurnSub: "进去了,快选座位!", enterSeats: "立即选座", min: "分", sec: "秒",
    s5Eyebrow: "第 5 步 — 选座", s5Title: "选择你的座位", s5Sub: "点击可用座位,我已高亮性价比最高、视野好的位置。",
    s5Ai: "进来了!我扫描了全场 — 蓝色发光的座位是价格与视野的最佳平衡,抓紧。",
    stage: "舞台", available: "可选", taken: "已售", yourPick: "你的选择", recommend: "小队推荐",
    seatsSelected: "个座位已选", selectSeatsHint: "最多选 2 个座位", seatSummary: "已选座位", subtotal: "小计", toPayment: "去付款",
    s6Eyebrow: "第 6 步 — 付款", s6Title: "最后一步 — 结账", s6Sub: "座位为你保留 7:00,完成付款即锁定。",
    s6Ai: "座位只保留 7 分钟,在计时结束前完成付款吧,我已预填好你的信息。",
    held: "座位保留中", orderSummary: "订单摘要", bookingFee: "预订费", total: "合计",
    payMethod: "支付方式", card: "银行卡", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "卡号", cardPh: "1234 5678 9012 3456", expiry: "有效期", expPh: "MM/YY", cvc: "CVC", cvcPh: "•••",
    agree: "我同意购票条款及不退款政策", payNow: "支付", processing: "正在为你锁定座位…",
    doneEyebrow: "预订成功", doneTitle: "抢到票啦!🎉", doneSub: "小队带你以最快速度走完 6 步,电子票已就绪。",
    doneAi: "成功了!票已到手。我已把电子票发到你邮箱,并加入了日历。看演唱会愉快!",
    bookingNo: "预订号", eTicket: "电子票", seatLabel: "座位", addCalendar: "加入日历",
    viewTickets: "查看电子票", bookAnother: "再订一场", timeTaken: "与小队的总用时", admitOne: "入场",
  },

  ko: {
    code: "KO",
    appTag: "AI 티켓팅 코파일럿",
    aiName: "메이트",
    aiStatus: "온라인 · 함께하는 중",
    next: "계속하기", back: "뒤로", confirm: "확인", step: "단계", of: "/",
    introEyebrow: "TickeMate AI에 오신 걸 환영해요",
    introTitle: "이제 티켓팅 전쟁,\n지지 않아요.",
    introSub: "저는 메이트, 당신의 AI 코파일럿이에요. 팬클럽 선예매부터 결제까지 예매의 모든 단계를 함께 안내해서, 원하는 좌석을 패닉 없이 잡게 도와드릴게요.",
    introBullet1: "실시간 대기열 전략", introBullet2: "자동 입력 & 본인 인증", introBullet3: "스마트 좌석 추천",
    introCta: "예매 시작하기", introNote: "데모 · 실제 결제는 진행되지 않아요",
    s1: "콘서트", s2: "계정", s3: "팬클럽", s4: "대기열", s5: "좌석", s6: "결제",
    s1Eyebrow: "STEP 1 — 공연 선택", s1Title: "오늘 우리가 잡을 공연은?", s1Sub: "노리는 공연을 골라주세요. 그 판매에 맞춰 전부 준비해둘게요.",
    s1Ai: "먼저 공연부터 골라봐요. 원하는 콘서트를 탭하면, 그 공연의 선예매와 타이밍을 딱 맞춰 준비할게요.",
    hot: "인기", from: "부터", select: "선택", selected: "선택됨",
    s2Eyebrow: "STEP 2 — 계정", s2Title: "계정부터 준비해요", s2Sub: "오픈 전에 인증된 계정이 필요해요. 가능한 건 제가 자동으로 채울게요.",
    s2Ai: "티켓팅은 로그인에서 갈려요. 오픈하자마자 바로 들어갈 수 있게, 지금 인증 계정을 만들어둬요.",
    s2a: "이메일", s2aSub: "여기로 인증 코드를 보낼게요", s2b: "인증", s2bSub: "전송된 6자리 코드를 입력하세요", s2c: "비밀번호", s2cSub: "강하게 — 오픈일엔 빠르게 움직여야 해요",
    s2d: "프로필", s2dSub: "신분증과 동일한 실명 (입장 시 필요)", s2e: "휴대폰", s2eSub: "오픈 알림 & 본인 확인용",
    emailPh: "you@email.com", codePh: "0 0 0 0 0 0", pwPh: "8자 이상", namePh: "이름", phonePh: "010-0000-0000",
    resend: "코드 재전송", autofill: "메이트가 자동 입력했어요", verified: "인증 완료", accountReady: "계정 인증 완료 · 준비됐어요",
    s3Eyebrow: "STEP 3 — 팬클럽", s3Title: "선예매를 위해 팬클럽에 가입해요", s3Sub: "회원은 48시간 먼저 선예매에 입장해요 — 좋은 좌석은 거기서 나가요.",
    s3Ai: "비밀 하나 알려드릴게요. 가장 좋은 좌석은 선예매에서 팔려요. 공식 팬클럽 가입이 그 문을 열어줘요. 아래 멤버십을 추천해요.",
    s3Benefit1: "48시간 빠른 선예매 입장", s3Benefit2: "회원 전용 좌석 블록", s3Benefit3: "평균적으로 낮은 대기번호", s3Benefit4: "전용 멤버십 카드 & 혜택",
    membership: "공식 멤버십", perYear: "/ 년", joinNow: "가입하고 선예매 열기", joined: "멤버십 활성화", memberNo: "회원번호",
    s4Eyebrow: "STEP 4 — 대기실", s4Title: "대기열에 입장했어요", s4Sub: "이 페이지에 머물러 주세요. 새로고침하거나 나가면 맨 뒤로 가요.",
    s4Ai: "판매가 시작됐고 지금 대기열에 있어요. 절대 새로고침하지 마세요 — 제가 자리를 지키고, 차례가 오면 바로 알려드릴게요.",
    queuePosition: "내 순서", peopleAhead: "명이 앞에 있어요", estWait: "예상 대기 시간", queueTip: "메이트가 자리를 지키고 있어요 — 잠시만요.",
    yourTurn: "당신 차례예요!", yourTurnSub: "입장했어요. 좌석을 빠르게 잡아봐요.", enterSeats: "지금 좌석 선택", min: "분", sec: "초",
    s5Eyebrow: "STEP 5 — 좌석 선택", s5Title: "좌석을 골라요", s5Sub: "비어 있는 좌석을 탭하세요. 가성비 좋고 시야 좋은 자리를 강조해뒀어요.",
    s5Ai: "들어왔어요! 좌석 맵을 스캔했어요 — 파랗게 빛나는 좌석이 가격과 시야의 밸런스가 가장 좋아요. 사라지기 전에 잡으세요.",
    stage: "무대", available: "선택 가능", taken: "매진", yourPick: "내 선택", recommend: "메이트 추천",
    seatsSelected: "석 선택됨", selectSeatsHint: "최대 2석까지 선택", seatSummary: "선택한 좌석", subtotal: "소계", toPayment: "결제하러 가기",
    s6Eyebrow: "STEP 6 — 결제", s6Title: "마지막 단계 — 결제", s6Sub: "좌석은 7:00 동안 잡혀 있어요. 결제를 완료해 확정하세요.",
    s6Ai: "좌석은 예약됐지만 딱 7분이에요. 타이머가 끝나기 전에 결제를 끝내요 — 정보는 미리 채워뒀어요.",
    held: "좌석 확보됨", orderSummary: "주문 요약", bookingFee: "예매 수수료", total: "총 결제금액",
    payMethod: "결제 수단", card: "카드", kakao: "카카오페이", naver: "네이버페이",
    cardNo: "카드 번호", cardPh: "1234 5678 9012 3456", expiry: "유효기간", expPh: "MM/YY", cvc: "CVC", cvcPh: "•••",
    agree: "티켓 약관 및 환불 불가 정책에 동의합니다", payNow: "결제하기", processing: "좌석을 확보하는 중…",
    doneEyebrow: "예매 완료", doneTitle: "티켓 잡았어요! 🎉", doneSub: "메이트와 함께 6단계를 최단 기록으로 끝냈어요. e-티켓이 준비됐어요.",
    doneAi: "해냈어요! 티켓 확보 완료. e-티켓을 이메일로 보냈고 공연을 캘린더에도 추가했어요. 콘서트 즐기세요!",
    bookingNo: "예매 번호", eTicket: "E-티켓", seatLabel: "좌석", addCalendar: "캘린더에 추가",
    viewTickets: "e-티켓 보기", bookAnother: "다른 공연 예매", timeTaken: "메이트와 함께한 총 시간", admitOne: "입장",
  },
};

/* ---- Platforms (links are real domains; demo only) ---- */
const PLATFORMS = [
  { key: "weverse", name: "Weverse", url: "https://account.weverse.io" },
  { key: "nol", name: "NOL · Interpark", url: "https://tickets.interpark.com" },
  { key: "yes24", name: "YES24 Ticket", url: "https://ticket.yes24.com" },
  { key: "melon", name: "Melon Ticket", url: "https://ticket.melon.com" },
];

const TZ_LIST = [
  "Asia/Seoul", "Asia/Tokyo", "Asia/Taipei", "Asia/Hong_Kong",
  "Asia/Bangkok", "Asia/Jakarta", "Asia/Manila", "Asia/Singapore",
  "Europe/London", "America/New_York", "America/Los_Angeles", "Australia/Sydney",
];
const TZ_LABEL = {
  "Asia/Seoul": "Seoul", "Asia/Tokyo": "Tokyo", "Asia/Taipei": "Taipei", "Asia/Hong_Kong": "Hong Kong",
  "Asia/Bangkok": "Bangkok", "Asia/Jakarta": "Jakarta", "Asia/Manila": "Manila", "Asia/Singapore": "Singapore",
  "Europe/London": "London", "America/New_York": "New York", "America/Los_Angeles": "Los Angeles", "Australia/Sydney": "Sydney",
};
const CARD_COUNTRIES = ["KR", "US", "JP", "CN", "TW", "HK", "PH", "ID", "TH", "SG", "MY", "VN", "GB", "AU", "CA", "FR", "DE"];
const CARD_ISSUERS = ["Visa", "Mastercard", "Amex", "JCB", "UnionPay"];

/* ---- Step 2 module strings, per language ---- */
const S2X = {
  ko: {
    s2Title: "예매 전, 계정 상태부터 점검해요",
    s2Sub: "해외 팬이 가장 많이 막히는 4가지를 미리 확인해 현장 수령 거부와 결제 실패를 예방해요.",
    s2Ai: "사실 티켓팅은 오픈 전에 절반이 갈려요. 플랫폼 이름 표기, 여권 유효기간, 해외 카드 결제, 그리고 오픈 알림까지 — 네 가지를 지금 같이 점검해둘게요.",
    checklist: "준비 체크리스트", doneOf: "완료", reviewed: "점검됨", toReview: "점검 필요",
    tabHealth: "계정 점검", tabPassport: "여권", tabPay: "결제 수단", tabAlert: "알림 설정",

    hTitle: "계정 상태 점검", hSub: "플랫폼마다 등록한 영문 이름이 조금만 달라도 본인 확인에서 막혀요. 네 곳의 등록명을 비교해드릴게요.",
    hHint: "여권 영문 이름과 동일하게", hCheck: "이름 일치 점검", hRecheck: "다시 점검",
    hMatchAll: "모든 플랫폼 이름이 일치해요", hIssues: "곳에서 불일치를 발견했어요",
    stOk: "일치", stCase: "대소문자 불일치", stOrder: "성·이름 순서 불일치", stSpace: "공백 오류", stName: "이름 불일치", stEmpty: "미입력",
    reference: "기준",
    fixCase: "대소문자만 달라요. 여권과 동일하게 통일하세요 (권장: 전부 대문자).",
    fixOrder: "성과 이름 순서가 달라요. 여권 표기 순서(성 → 이름)로 맞추세요.",
    fixSpace: "전각 공백 또는 불필요한 공백이 있어요. 반각 공백 하나로 수정하세요.",
    fixName: "다른 이름이 등록돼 있어요. 여권 영문명으로 변경하세요.",
    openSettings: "설정 열기",
    hWhy: "현장 수령 시 신분증·여권과 예매자명이 다르면 입장이 거부될 수 있어요. 네 곳을 여권 영문명으로 통일하세요.",

    pTitle: "여권 유효성 트래커", pSub: "예매 시 등록한 여권 번호와 만료일을 입력하면, 공연일 기준으로 유효성을 계산해드려요.",
    pNo: "여권 번호", pNoPh: "M12345678", pExp: "여권 만료일", pConcert: "공연일", pCheck: "유효성 확인",
    pOk: "공연일 기준 유효해요", pWarn: "곧 만료돼요 — 갱신을 권장해요", pBad: "공연 전에 만료돼요 — 갱신이 필요해요",
    pMonths: "공연일 기준 잔여", pMonthsUnit: "개월", p6mo: "한국 입국은 잔여 유효기간 6개월 이상을 권장해요.",
    pPickupT: "현장 수령 거부 방지", pPickupB: "여권 번호가 예매 정보와 다르면 티켓 수령이 거부돼요. 갱신했다면 반드시 예매 정보를 먼저 업데이트하세요.",
    pRenewT: "여권 번호가 바뀌었다면", pRenewB: "신·구 번호가 다를 때: ① 예매처 고객센터에 번호 변경 요청 ② (가능하면) 구 여권 지참 ③ 영문명 일치 재확인.",

    payTitle: "결제 수단 사전 점검", paySub: "보유 카드의 발급 국가와 브랜드를 입력하면, 해외 카드 지원 여부와 3D Secure 필요 여부를 알려드려요.",
    payCountry: "카드 발급 국가", payIssuer: "카드 브랜드", payCheck: "결제 수단 점검",
    pay3dsT: "3D Secure 인증 필수", pay3dsB: "해외 발급 카드는 결제 시 3D Secure(해외 인증)가 필요해요. 카드사 앱에서 미리 활성화해 두세요.",
    paySupOk: "주요 플랫폼 사용 가능", paySupPartial: "일부 플랫폼만 지원", paySupLimited: "지원이 제한적이에요",
    payAltT: "권장 대안 결제 수단",
    payAlt1: "카카오페이 / 네이버페이 (한국 휴대폰 번호 필요)",
    payAlt2: "예매 전 원화 충전형 선불카드 준비",
    payAlt3: "멀티커런시 카드로 원화 환전 사전 준비",
    payAlt4: "한국 지인 대리 결제 시 예매자명 일치 확인",
    issVisa: "Visa·Mastercard는 3D Secure 인증 시 대부분 사용 가능해요.",
    issJCB: "JCB는 일부 플랫폼만 지원하니 대안을 함께 준비하세요.",
    issUP: "UnionPay(은련)는 지원이 들쭉날쭉해요. 대안을 권장해요.",
    issAmex: "Amex는 국내 티켓팅에서 거부되는 경우가 많아요. 대안을 권장해요.",

    aTitle: "공연 정보 등록 + 알림 설정", aSub: "예매 오픈 일시를 등록하면, 당신의 시간대로 변환해 단계별 알림을 보내드려요.",
    aShow: "공연명", aOpen: "예매 오픈 (KST)", aPlatform: "타겟 플랫폼", aTz: "내 시간대",
    aWhen: "알림 받을 시점", a1: "오픈 D-1", aD: "당일 오전", a30: "오픈 30분 전", a10: "오픈 10분 전",
    aLocal: "내 시간대 기준 발송 시각", aSave: "알림 저장", aResave: "알림 수정",
    aSaved: "개 알림이 예약됐어요", aOpenLocal: "내 시간대 기준 오픈",
  },
  en: {
    s2Title: "Let's check your account readiness first",
    s2Sub: "Four things that trip up international fans most — sorted now to avoid venue pickup rejections and failed payments.",
    s2Ai: "Honestly, half of ticket wars are lost before the sale even opens. Name spelling across platforms, passport validity, foreign-card payment, and open-time alerts — let's check all four right now.",
    checklist: "Readiness checklist", doneOf: "done", reviewed: "Reviewed", toReview: "To review",
    tabHealth: "Account", tabPassport: "Passport", tabPay: "Payment", tabAlert: "Alerts",

    hTitle: "Account health check", hSub: "If your romanized name differs even slightly between platforms, identity checks fail. I'll compare your registered name across all four.",
    hHint: "Match your passport exactly", hCheck: "Check name match", hRecheck: "Re-check",
    hMatchAll: "All platform names match", hIssues: "mismatch(es) found",
    stOk: "Match", stCase: "Case mismatch", stOrder: "Surname/given order", stSpace: "Spacing error", stName: "Name mismatch", stEmpty: "Empty",
    reference: "reference",
    fixCase: "Only the letter case differs. Make it identical to your passport (recommended: ALL CAPS).",
    fixOrder: "Surname and given name are in different order. Match the passport order (surname → given).",
    fixSpace: "There's a full-width or extra space. Replace it with a single half-width space.",
    fixName: "A different name is registered. Change it to your passport name.",
    openSettings: "Open settings",
    hWhy: "At venue pickup, if your ID/passport name differs from the booking name, entry can be refused. Unify all four to your passport name.",

    pTitle: "Passport validity tracker", pSub: "Enter the passport number & expiry you booked with, and I'll check validity against the show date.",
    pNo: "Passport number", pNoPh: "M12345678", pExp: "Expiry date", pConcert: "Show date", pCheck: "Check validity",
    pOk: "Valid on the show date", pWarn: "Expiring soon — renewal recommended", pBad: "Expires before the show — renewal needed",
    pMonths: "Remaining at show date", pMonthsUnit: "months", p6mo: "Korea entry recommends 6+ months of remaining validity.",
    pPickupT: "Avoid pickup rejection", pPickupB: "If the passport number differs from your booking, ticket pickup is refused. If you renewed, update your booking info first.",
    pRenewT: "If your passport number changed", pRenewB: "When old & new numbers differ: ① ask the seller to update the number ② bring the old passport if possible ③ re-confirm the romanized name matches.",

    payTitle: "Payment method pre-check", paySub: "Enter your card's issuing country & brand, and I'll flag foreign-card support and whether 3D Secure is required.",
    payCountry: "Card issuing country", payIssuer: "Card brand", payCheck: "Check payment",
    pay3dsT: "3D Secure required", pay3dsB: "Foreign-issued cards need 3D Secure (overseas authentication) at checkout. Enable it in your card app in advance.",
    paySupOk: "Works on major platforms", paySupPartial: "Some platforms only", paySupLimited: "Support is limited",
    payAltT: "Recommended alternatives",
    payAlt1: "KakaoPay / NaverPay (needs a Korean phone number)",
    payAlt2: "Prepare a KRW prepaid card before the sale",
    payAlt3: "Use a multi-currency card with KRW exchanged in advance",
    payAlt4: "If a Korean friend pays, confirm the booking name matches",
    issVisa: "Visa & Mastercard usually work with 3D Secure enabled.",
    issJCB: "JCB is only supported on some platforms — prepare a backup.",
    issUP: "UnionPay support is inconsistent. An alternative is recommended.",
    issAmex: "Amex is often declined by Korean ticketing. An alternative is recommended.",

    aTitle: "Concert info + alert setup", aSub: "Register the on-sale time and I'll convert it to your timezone and send staged reminders.",
    aShow: "Concert", aOpen: "On-sale (KST)", aPlatform: "Target platform", aTz: "Your timezone",
    aWhen: "Remind me at", a1: "D-1", aD: "Day-of morning", a30: "30 min before", a10: "10 min before",
    aLocal: "Send time in your timezone", aSave: "Save alerts", aResave: "Edit alerts",
    aSaved: "alert(s) scheduled", aOpenLocal: "On-sale in your timezone",
  },
  ja: {
    s2Title: "予約前に、アカウント状態を点検しましょう",
    s2Sub: "海外ファンが最も詰まりやすい4点を事前に確認し、現地受取拒否と決済失敗を防ぎます。",
    s2Ai: "実はチケット戦争は、開始前に半分が決まります。プラットフォーム間の名前表記、パスポートの有効期限、海外カード決済、開始アラート — この4つを今いっしょに点検しておきましょう。",
    checklist: "準備チェックリスト", doneOf: "完了", reviewed: "点検済み", toReview: "要点検",
    tabHealth: "アカウント", tabPassport: "パスポート", tabPay: "決済手段", tabAlert: "アラート",

    hTitle: "アカウント状態の点検", hSub: "プラットフォームごとにローマ字名がわずかでも違うと本人確認で弾かれます。4か所の登録名を比較します。",
    hHint: "パスポートと完全一致で", hCheck: "名前一致を点検", hRecheck: "再点検",
    hMatchAll: "全プラットフォームの名前が一致", hIssues: "か所で不一致を発見",
    stOk: "一致", stCase: "大小文字不一致", stOrder: "姓・名の順序", stSpace: "空白エラー", stName: "名前不一致", stEmpty: "未入力",
    reference: "基準",
    fixCase: "大小文字のみ違います。パスポートと同一に統一してください（推奨：すべて大文字）。",
    fixOrder: "姓と名の順序が違います。パスポート順（姓 → 名）に合わせてください。",
    fixSpace: "全角または余分な空白があります。半角スペース1つに修正してください。",
    fixName: "別の名前が登録されています。パスポートのローマ字名に変更してください。",
    openSettings: "設定を開く",
    hWhy: "現地受取時、身分証・パスポートと予約名が違うと入場を断られることがあります。4か所をパスポート名に統一してください。",

    pTitle: "パスポート有効性トラッカー", pSub: "予約時のパスポート番号と有効期限を入力すると、公演日基準で有効性を計算します。",
    pNo: "パスポート番号", pNoPh: "M12345678", pExp: "有効期限", pConcert: "公演日", pCheck: "有効性を確認",
    pOk: "公演日時点で有効です", pWarn: "まもなく失効 — 更新を推奨", pBad: "公演前に失効 — 更新が必要",
    pMonths: "公演日時点の残り", pMonthsUnit: "か月", p6mo: "韓国入国は残存有効期間6か月以上を推奨します。",
    pPickupT: "受取拒否を防ぐ", pPickupB: "パスポート番号が予約情報と違うと受取が拒否されます。更新した場合は先に予約情報を更新してください。",
    pRenewT: "番号が変わった場合", pRenewB: "新旧番号が違うとき：① 販売元へ番号変更を依頼 ②（可能なら）旧パスポート持参 ③ ローマ字名の一致を再確認。",

    payTitle: "決済手段の事前点検", paySub: "カードの発行国とブランドを入力すると、海外カード対応と3D Secureの要否をお知らせします。",
    payCountry: "カード発行国", payIssuer: "カードブランド", payCheck: "決済を点検",
    pay3dsT: "3D Secure必須", pay3dsB: "海外発行カードは決済時に3D Secure（海外認証）が必要です。カードアプリで事前に有効化してください。",
    paySupOk: "主要プラットフォームで利用可", paySupPartial: "一部のみ対応", paySupLimited: "対応が限定的",
    payAltT: "推奨の代替手段",
    payAlt1: "KakaoPay / NaverPay（韓国の電話番号が必要）",
    payAlt2: "予約前にウォン建てプリペイドを準備",
    payAlt3: "マルチカレンシーカードでウォンを事前両替",
    payAlt4: "韓国の知人が代理決済する場合、予約名の一致を確認",
    issVisa: "Visa・Mastercardは3D Secure有効化でほぼ利用可能です。",
    issJCB: "JCBは一部のみ対応。バックアップを準備してください。",
    issUP: "UnionPayは対応が不安定。代替を推奨します。",
    issAmex: "Amexは国内チケッティングで拒否されがち。代替を推奨します。",

    aTitle: "公演情報の登録 + アラート設定", aSub: "発売時刻を登録すると、あなたの時間帯に変換して段階的に通知します。",
    aShow: "公演名", aOpen: "発売 (KST)", aPlatform: "対象プラットフォーム", aTz: "あなたの時間帯",
    aWhen: "通知タイミング", a1: "発売前日", aD: "当日午前", a30: "発売30分前", a10: "発売10分前",
    aLocal: "あなたの時間帯での送信時刻", aSave: "アラートを保存", aResave: "アラートを編集",
    aSaved: "件のアラートを予約", aOpenLocal: "あなたの時間帯での発売",
  },
  zh: {
    s2Title: "开售前，先检查账户状态",
    s2Sub: "海外粉丝最容易卡住的 4 件事,提前确认,避免现场取票被拒和付款失败。",
    s2Ai: "其实抢票一半在开售前就分胜负了。各平台姓名拼写、护照有效期、海外卡付款,还有开售提醒 —— 这四项现在一起检查好。",
    checklist: "准备清单", doneOf: "完成", reviewed: "已检查", toReview: "待检查",
    tabHealth: "账户", tabPassport: "护照", tabPay: "支付方式", tabAlert: "提醒",

    hTitle: "账户状态检查", hSub: "各平台的英文名只要有一点不同,身份核验就会失败。我会比对四个平台的登记姓名。",
    hHint: "与护照完全一致", hCheck: "检查姓名一致", hRecheck: "重新检查",
    hMatchAll: "所有平台姓名一致", hIssues: "处发现不一致",
    stOk: "一致", stCase: "大小写不一致", stOrder: "姓名顺序不一致", stSpace: "空格错误", stName: "姓名不一致", stEmpty: "未填写",
    reference: "基准",
    fixCase: "仅大小写不同。请与护照统一(建议全部大写)。",
    fixOrder: "姓与名顺序不同。请按护照顺序(姓 → 名)统一。",
    fixSpace: "含全角或多余空格。请改为一个半角空格。",
    fixName: "登记了不同的姓名。请改为护照英文名。",
    openSettings: "打开设置",
    hWhy: "现场取票时,若证件/护照与预订姓名不同,可能被拒绝入场。请将四个平台统一为护照英文名。",

    pTitle: "护照有效性追踪", pSub: "输入预订时登记的护照号与到期日,我会按演出日计算有效性。",
    pNo: "护照号码", pNoPh: "M12345678", pExp: "到期日", pConcert: "演出日", pCheck: "检查有效性",
    pOk: "演出日仍然有效", pWarn: "即将到期 — 建议更换", pBad: "演出前到期 — 需要更换",
    pMonths: "演出日剩余", pMonthsUnit: "个月", p6mo: "入境韩国建议剩余有效期 6 个月以上。",
    pPickupT: "避免取票被拒", pPickupB: "护照号与预订信息不符会被拒绝取票。若已换发,请先更新预订信息。",
    pRenewT: "若护照号已变更", pRenewB: "新旧号码不同时:① 联系售票方变更号码 ②(可能的话)携带旧护照 ③ 再次确认英文名一致。",

    payTitle: "支付方式预检", paySub: "输入卡的发行国家与品牌,我会提示海外卡支持情况及是否需要 3D Secure。",
    payCountry: "发卡国家", payIssuer: "卡品牌", payCheck: "检查支付",
    pay3dsT: "需要 3D Secure", pay3dsB: "海外发行卡结账时需要 3D Secure(海外验证)。请提前在银行 App 中开启。",
    paySupOk: "主流平台可用", paySupPartial: "仅部分平台支持", paySupLimited: "支持有限",
    payAltT: "推荐替代方式",
    payAlt1: "KakaoPay / NaverPay(需韩国手机号)",
    payAlt2: "开售前准备韩元充值预付卡",
    payAlt3: "用多币种卡提前兑换韩元",
    payAlt4: "请韩国朋友代付时,确认预订姓名一致",
    issVisa: "Visa、Mastercard 开启 3D Secure 后大多可用。",
    issJCB: "JCB 仅部分平台支持,请准备备用方式。",
    issUP: "银联支持不稳定,建议使用替代方式。",
    issAmex: "Amex 在韩国购票常被拒,建议使用替代方式。",

    aTitle: "演出信息登记 + 提醒设置", aSub: "登记开售时间,我会转换为你的时区并分阶段提醒。",
    aShow: "演出名称", aOpen: "开售 (KST)", aPlatform: "目标平台", aTz: "你的时区",
    aWhen: "提醒时间点", a1: "开售前 1 天", aD: "当天上午", a30: "开售前 30 分钟", a10: "开售前 10 分钟",
    aLocal: "按你的时区发送时间", aSave: "保存提醒", aResave: "修改提醒",
    aSaved: "条提醒已预约", aOpenLocal: "你的时区开售时间",
  },
};
Object.keys(S2X).forEach((k) => { const { s2Title, s2Sub, s2Ai, ...rest } = S2X[k]; Object.assign(T[k], { s2Title, s2Sub, s2Ai, s2x: rest }); });

function formatPrice(n, lang) {
  if (lang === "ko") return n.toLocaleString("ko-KR") + "원";
  return "₩" + n.toLocaleString("en-US");
}

/* Languages offered in the switcher (native names) */
const LANGS = [
  { code: "ko", label: "한국어", short: "KO" },
  { code: "en", label: "English", short: "EN" },
  { code: "ja", label: "日本語", short: "JA" },
  { code: "zh", label: "中文", short: "ZH" },
  { code: "es", label: "Español", short: "ES" },
  { code: "pt", label: "Português", short: "PT" },
  { code: "th", label: "ภาษาไทย", short: "TH" },
  { code: "id", label: "Bahasa Indonesia", short: "ID" },
  { code: "fr", label: "Français", short: "FR" },
  { code: "tl", label: "Tagalog", short: "TL" },
];

window.TM = { CONCERTS, SEAT_TIERS, T, formatPrice, LANGS, PLATFORMS, TZ_LIST, TZ_LABEL, CARD_COUNTRIES, CARD_ISSUERS };
