/* ===========================================================
   TickeMate AI — additional languages
   ES / PT / TH / ID / FR / TL
   Core flow strings translated; the detailed Step-2 module
   (s2x) falls back to English so nothing renders blank.
   =========================================================== */
(function () {
  const T = window.TM.T;

  const ES = {
    code: "ES", appTag: "Copiloto de entradas con IA", aiName: "Mate", aiStatus: "en línea · guiándote",
    next: "Continuar", back: "Atrás", confirm: "Confirmar", step: "Paso", of: "de",
    introEyebrow: "Bienvenido a TickeMate AI", introTitle: "Nunca más pierdas una guerra de entradas.",
    introSub: "Soy Mate, tu copiloto con IA. Te guío en cada paso de la compra, desde la preventa del club de fans hasta el pago, para que consigas tu asiento sin pánico.",
    introBullet1: "Estrategia de cola en tiempo real", introBullet2: "Formularios y verificación automáticos", introBullet3: "Recomendaciones de asiento inteligentes",
    introCta: "Empezar la compra", introNote: "Demo · no se procesa ningún pago real",
    s1: "Concierto", s2: "Cuenta", s3: "Club de fans", s4: "Cola", s5: "Asientos", s6: "Pago",
    s1Eyebrow: "Paso 1 — Elige tu show", s1Title: "¿Qué concierto vamos a ganar hoy?", s1Sub: "Elige el show que quieres. Lo prepararé todo para esa venta.",
    s1Ai: "Empecemos por el show. Toca el concierto que quieres y prepararé la preventa y los tiempos.",
    hot: "POPULAR", from: "desde", select: "Elegir", selected: "Elegido",
    s2a: "Correo", s2aSub: "Te enviaremos un código de verificación aquí", s2b: "Verificar", s2bSub: "Introduce el código de 6 dígitos",
    s2c: "Contraseña", s2cSub: "Hazla fuerte — irás rápido el día de la venta", s2d: "Perfil", s2dSub: "Nombre real como en tu documento (obligatorio para entrar)",
    s2e: "Teléfono", s2eSub: "Para avisos del día de venta y verificación",
    emailPh: "tu@correo.com", codePh: "0 0 0 0 0 0", pwPh: "8+ caracteres", namePh: "Nombre completo", phonePh: "+34 600 000 000",
    resend: "Reenviar código", autofill: "Mate lo rellenó", verified: "Verificado", accountReady: "Cuenta verificada y lista",
    s3Eyebrow: "Paso 3 — Club de fans", s3Title: "Únete al club para acceso a preventa", s3Sub: "Los socios entran 48 h antes — ahí se van los mejores asientos.",
    s3Ai: "El secreto: los mejores asientos se venden en preventa. Unirte al club oficial la desbloquea. Te recomiendo la membresía de abajo.",
    s3Benefit1: "Acceso a preventa 48 h antes", s3Benefit2: "Bloque de asientos solo para socios", s3Benefit3: "Números de cola más bajos de media", s3Benefit4: "Tarjeta de socio y ventajas exclusivas",
    membership: "MEMBRESÍA OFICIAL", perYear: "/ año", joinNow: "Unirse y abrir preventa", joined: "Membresía activa", memberNo: "N.º de socio",
    s4Eyebrow: "Paso 4 — Sala de espera", s4Title: "Estás en la cola", s4Sub: "Quédate en esta página. Recargar o salir te manda al final.",
    s4Ai: "La venta está activa y estás en la cola. NO recargues — guardo tu lugar y te aviso cuando sea tu turno.",
    queuePosition: "Tu posición", peopleAhead: "personas delante de ti", estWait: "Espera estimada", queueTip: "Mate guarda tu sitio — tranquilo.",
    yourTurn: "¡Es tu turno!", yourTurnSub: "Estás dentro. A por esos asientos — rápido.", enterSeats: "Elegir asientos ya", min: "min", sec: "seg",
    s5Eyebrow: "Paso 5 — Selección de asiento", s5Title: "Elige tus asientos", s5Sub: "Toca un asiento disponible. He marcado la mejor relación precio-vista.",
    s5Ai: "¡Estamos dentro! Escaneé el mapa — los asientos en azul son el mejor equilibrio precio-vista. Cógelos antes de que vuelen.",
    stage: "ESCENARIO", available: "Disponible", taken: "Ocupado", yourPick: "Tu elección", recommend: "Elección de Mate",
    seatsSelected: "asientos elegidos", selectSeatsHint: "Elige hasta 2 asientos", seatSummary: "Asientos elegidos", subtotal: "Subtotal", toPayment: "Ir al pago",
    s6Eyebrow: "Paso 6 — Pago", s6Title: "Último paso — pagar", s6Sub: "Tus asientos están reservados 7:00. Completa el pago para asegurarlos.",
    s6Ai: "Los asientos están reservados pero solo 7 minutos. Terminemos el pago antes de que acabe el tiempo — ya rellené tus datos.",
    held: "Asientos reservados", orderSummary: "Resumen del pedido", bookingFee: "Gastos de gestión", total: "Total",
    payMethod: "Método de pago", card: "Tarjeta", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "Número de tarjeta", cardPh: "1234 5678 9012 3456", expiry: "Caducidad", expPh: "MM/AA", cvc: "CVC", cvcPh: "•••",
    agree: "Acepto los términos y la política de no reembolso", payNow: "Pagar", processing: "Asegurando tus asientos…",
    doneEyebrow: "Compra confirmada", doneTitle: "¡Conseguiste las entradas! 🎉", doneSub: "Mate te guió por 6 pasos en tiempo récord. Tus e-tickets están listos.",
    doneAi: "¡Lo logramos! Entradas aseguradas. Envié los e-tickets a tu correo y añadí el show a tu calendario. ¡Disfruta el concierto!",
    bookingNo: "Número de reserva", eTicket: "E-TICKET", seatLabel: "Asiento", addCalendar: "Añadir al calendario",
    viewTickets: "Ver e-tickets", bookAnother: "Reservar otro show", timeTaken: "Tiempo total con Mate", admitOne: "ADMISIÓN",
    s2Title: "Primero revisemos que tu cuenta esté lista",
    s2Sub: "Cuatro cosas que más complican a los fans internacionales — resueltas ahora para evitar rechazos al recoger y pagos fallidos.",
    s2Ai: "La verdad, media guerra de entradas se pierde antes de abrir la venta. La escritura del nombre entre plataformas, la validez del pasaporte, el pago con tarjeta extranjera y los avisos de apertura — revisemos los cuatro ahora.",
  };

  const PT = {
    code: "PT", appTag: "Copiloto de bilheteria com IA", aiName: "Mate", aiStatus: "online · te guiando",
    next: "Continuar", back: "Voltar", confirm: "Confirmar", step: "Etapa", of: "de",
    introEyebrow: "Bem-vindo ao TickeMate AI", introTitle: "Nunca mais perca uma guerra de ingressos.",
    introSub: "Sou o Mate, seu copiloto com IA. Vou te guiar em cada etapa da compra, da pré-venda do fã-clube ao pagamento, para você garantir seu lugar sem pânico.",
    introBullet1: "Estratégia de fila em tempo real", introBullet2: "Formulários e verificação automáticos", introBullet3: "Recomendações de assento inteligentes",
    introCta: "Começar a compra", introNote: "Demo · nenhum pagamento real é processado",
    s1: "Show", s2: "Conta", s3: "Fã-clube", s4: "Fila", s5: "Assentos", s6: "Pagamento",
    s1Eyebrow: "Etapa 1 — Escolha o show", s1Title: "Qual show vamos garantir hoje?", s1Sub: "Escolha o show que você quer. Vou preparar tudo para essa venda.",
    s1Ai: "Vamos começar pelo show. Toque no show que você quer e eu organizo a pré-venda e o horário.",
    hot: "EM ALTA", from: "a partir de", select: "Escolher", selected: "Escolhido",
    s2a: "E-mail", s2aSub: "Enviaremos um código de verificação aqui", s2b: "Verificar", s2bSub: "Digite o código de 6 dígitos",
    s2c: "Senha", s2cSub: "Faça forte — você vai correr no dia da venda", s2d: "Perfil", s2dSub: "Nome real como no documento (obrigatório para entrar)",
    s2e: "Telefone", s2eSub: "Para avisos do dia e verificação",
    emailPh: "voce@email.com", codePh: "0 0 0 0 0 0", pwPh: "8+ caracteres", namePh: "Nome completo", phonePh: "+55 11 90000-0000",
    resend: "Reenviar código", autofill: "Mate preencheu isto", verified: "Verificado", accountReady: "Conta verificada e pronta",
    s3Eyebrow: "Etapa 3 — Fã-clube", s3Title: "Entre no fã-clube para a pré-venda", s3Sub: "Membros entram 48 h antes — é onde vão os melhores lugares.",
    s3Ai: "O segredo: os melhores lugares saem na pré-venda. Entrar no fã-clube oficial libera ela. Recomendo a assinatura abaixo.",
    s3Benefit1: "Acesso à pré-venda 48 h antes", s3Benefit2: "Bloco de assentos só para membros", s3Benefit3: "Números de fila menores em média", s3Benefit4: "Cartão de membro e vantagens exclusivas",
    membership: "ASSINATURA OFICIAL", perYear: "/ ano", joinNow: "Entrar e liberar pré-venda", joined: "Assinatura ativa", memberNo: "N.º de membro",
    s4Eyebrow: "Etapa 4 — Sala de espera", s4Title: "Você está na fila", s4Sub: "Fique nesta página. Atualizar ou sair te manda para o fim.",
    s4Ai: "A venda começou e você está na fila. NÃO atualize — eu guardo seu lugar e aviso na sua vez.",
    queuePosition: "Sua posição", peopleAhead: "pessoas na sua frente", estWait: "Espera estimada", queueTip: "Mate está guardando seu lugar — calma.",
    yourTurn: "É a sua vez!", yourTurnSub: "Você entrou. Vamos pegar os lugares — rápido.", enterSeats: "Escolher assentos agora", min: "min", sec: "seg",
    s5Eyebrow: "Etapa 5 — Seleção de assento", s5Title: "Escolha seus assentos", s5Sub: "Toque num assento disponível. Destaquei o melhor custo-benefício com boa vista.",
    s5Ai: "Entramos! Escaneei o mapa — os assentos em azul têm o melhor equilíbrio de preço e vista. Pegue antes que acabem.",
    stage: "PALCO", available: "Disponível", taken: "Ocupado", yourPick: "Sua escolha", recommend: "Escolha do Mate",
    seatsSelected: "assentos escolhidos", selectSeatsHint: "Escolha até 2 assentos", seatSummary: "Assentos escolhidos", subtotal: "Subtotal", toPayment: "Ir para o pagamento",
    s6Eyebrow: "Etapa 6 — Pagamento", s6Title: "Última etapa — pagar", s6Sub: "Seus assentos estão reservados por 7:00. Conclua o pagamento para garantir.",
    s6Ai: "Os assentos estão reservados, mas só por 7 minutos. Vamos concluir o pagamento antes do tempo acabar — já preenchi seus dados.",
    held: "Assentos reservados", orderSummary: "Resumo do pedido", bookingFee: "Taxa de reserva", total: "Total",
    payMethod: "Forma de pagamento", card: "Cartão", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "Número do cartão", cardPh: "1234 5678 9012 3456", expiry: "Validade", expPh: "MM/AA", cvc: "CVC", cvcPh: "•••",
    agree: "Concordo com os termos e a política de não reembolso", payNow: "Pagar", processing: "Garantindo seus assentos…",
    doneEyebrow: "Compra confirmada", doneTitle: "Você conseguiu os ingressos! 🎉", doneSub: "Mate te guiou por 6 etapas em tempo recorde. Seus e-tickets estão prontos.",
    doneAi: "Conseguimos! Ingressos garantidos. Enviei os e-tickets para seu e-mail e adicionei o show ao calendário. Aproveite o show!",
    bookingNo: "Número da reserva", eTicket: "E-TICKET", seatLabel: "Assento", addCalendar: "Adicionar ao calendário",
    viewTickets: "Ver e-tickets", bookAnother: "Reservar outro show", timeTaken: "Tempo total com o Mate", admitOne: "ENTRADA",
    s2Title: "Primeiro, vamos checar se sua conta está pronta",
    s2Sub: "Quatro coisas que mais travam fãs internacionais — resolvidas agora para evitar recusa na retirada e pagamentos falhos.",
    s2Ai: "Sinceramente, metade da guerra de ingressos se perde antes da venda abrir. Grafia do nome entre plataformas, validade do passaporte, pagamento com cartão estrangeiro e alertas de abertura — vamos checar os quatro agora.",
  };

  const FR = {
    code: "FR", appTag: "Copilote billetterie IA", aiName: "Mate", aiStatus: "en ligne · je te guide",
    next: "Continuer", back: "Retour", confirm: "Confirmer", step: "Étape", of: "sur",
    introEyebrow: "Bienvenue sur TickeMate AI", introTitle: "Ne perds plus jamais une guerre de billets.",
    introSub: "Je suis Mate, ton copilote IA. Je t'accompagne à chaque étape, de la prévente du fan-club au paiement, pour décrocher ta place sans paniquer.",
    introBullet1: "Stratégie de file en temps réel", introBullet2: "Formulaires et vérification automatiques", introBullet3: "Recommandations de places malines",
    introCta: "Commencer la réservation", introNote: "Démo · aucun paiement réel n'est effectué",
    s1: "Concert", s2: "Compte", s3: "Fan-club", s4: "File", s5: "Places", s6: "Paiement",
    s1Eyebrow: "Étape 1 — Choisis ton concert", s1Title: "Quel concert on gagne aujourd'hui ?", s1Sub: "Choisis le concert visé. Je prépare tout pour cette vente.",
    s1Ai: "Commençons par le concert. Touche celui que tu veux, je cale la prévente et le timing.",
    hot: "POPULAIRE", from: "dès", select: "Choisir", selected: "Choisi",
    s2a: "E-mail", s2aSub: "On envoie un code de vérification ici", s2b: "Vérifier", s2bSub: "Saisis le code à 6 chiffres",
    s2c: "Mot de passe", s2cSub: "Fais-le solide — tu iras vite le jour J", s2d: "Profil", s2dSub: "Nom réel comme sur ta pièce d'identité (requis à l'entrée)",
    s2e: "Téléphone", s2eSub: "Pour les alertes du jour et la vérification",
    emailPh: "toi@email.com", codePh: "0 0 0 0 0 0", pwPh: "8+ caractères", namePh: "Nom complet", phonePh: "+33 6 00 00 00 00",
    resend: "Renvoyer le code", autofill: "Mate a rempli ceci", verified: "Vérifié", accountReady: "Compte vérifié et prêt",
    s3Eyebrow: "Étape 3 — Fan-club", s3Title: "Rejoins le fan-club pour la prévente", s3Sub: "Les membres entrent 48 h avant — c'est là que partent les meilleures places.",
    s3Ai: "Le secret : les meilleures places partent en prévente. Rejoindre le fan-club officiel la débloque. Je recommande l'abonnement ci-dessous.",
    s3Benefit1: "Accès prévente 48 h avant", s3Benefit2: "Bloc de places réservé aux membres", s3Benefit3: "Numéros de file plus bas en moyenne", s3Benefit4: "Carte de membre et avantages exclusifs",
    membership: "ABONNEMENT OFFICIEL", perYear: "/ an", joinNow: "Rejoindre et ouvrir la prévente", joined: "Abonnement actif", memberNo: "N° de membre",
    s4Eyebrow: "Étape 4 — Salle d'attente", s4Title: "Tu es dans la file", s4Sub: "Reste sur cette page. Actualiser ou partir te renvoie à la fin.",
    s4Ai: "La vente est lancée et tu es dans la file. NE recharge PAS — je garde ta place et te préviens à ton tour.",
    queuePosition: "Ta position", peopleAhead: "personnes devant toi", estWait: "Attente estimée", queueTip: "Mate garde ta place — patiente.",
    yourTurn: "C'est ton tour !", yourTurnSub: "Tu es dedans. On attrape ces places — vite.", enterSeats: "Choisir les places", min: "min", sec: "s",
    s5Eyebrow: "Étape 5 — Choix des places", s5Title: "Choisis tes places", s5Sub: "Touche une place libre. J'ai surligné le meilleur rapport prix-vue.",
    s5Ai: "On y est ! J'ai scanné le plan — les places en bleu offrent le meilleur équilibre prix-vue. Attrape-les vite.",
    stage: "SCÈNE", available: "Libre", taken: "Pris", yourPick: "Ton choix", recommend: "Choix de Mate",
    seatsSelected: "places choisies", selectSeatsHint: "Choisis jusqu'à 2 places", seatSummary: "Places choisies", subtotal: "Sous-total", toPayment: "Aller au paiement",
    s6Eyebrow: "Étape 6 — Paiement", s6Title: "Dernière étape — paiement", s6Sub: "Tes places sont réservées 7:00. Termine le paiement pour les bloquer.",
    s6Ai: "Les places sont réservées mais 7 minutes seulement. Finissons le paiement avant la fin du chrono — j'ai prérempli tes infos.",
    held: "Places réservées", orderSummary: "Récapitulatif", bookingFee: "Frais de réservation", total: "Total",
    payMethod: "Moyen de paiement", card: "Carte", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "Numéro de carte", cardPh: "1234 5678 9012 3456", expiry: "Expiration", expPh: "MM/AA", cvc: "CVC", cvcPh: "•••",
    agree: "J'accepte les conditions et la politique de non-remboursement", payNow: "Payer", processing: "Sécurisation de tes places…",
    doneEyebrow: "Réservation confirmée", doneTitle: "Tu as les billets ! 🎉", doneSub: "Mate t'a guidé en 6 étapes en un temps record. Tes e-billets sont prêts.",
    doneAi: "On l'a fait ! Billets sécurisés. J'ai envoyé les e-billets par e-mail et ajouté le concert à ton agenda. Profite du concert !",
    bookingNo: "Numéro de réservation", eTicket: "E-BILLET", seatLabel: "Place", addCalendar: "Ajouter à l'agenda",
    viewTickets: "Voir les e-billets", bookAnother: "Réserver un autre concert", timeTaken: "Temps total avec Mate", admitOne: "ADMISSION",
    s2Title: "D'abord, vérifions que ton compte est prêt",
    s2Sub: "Quatre choses qui bloquent le plus les fans internationaux — réglées maintenant pour éviter les refus au retrait et les paiements échoués.",
    s2Ai: "Franchement, la moitié des guerres de billets se perd avant l'ouverture. Orthographe du nom selon les plateformes, validité du passeport, paiement par carte étrangère et alertes d'ouverture — vérifions les quatre maintenant.",
  };

  const TH = {
    code: "TH", appTag: "ผู้ช่วย AI สำหรับจองตั๋ว", aiName: "เมต", aiStatus: "ออนไลน์ · กำลังช่วยคุณ",
    next: "ต่อไป", back: "ย้อนกลับ", confirm: "ยืนยัน", step: "ขั้นตอน", of: "จาก",
    introEyebrow: "ยินดีต้อนรับสู่ TickeMate AI", introTitle: "ไม่พลาดสงครามจองตั๋วอีกต่อไป",
    introSub: "ฉันคือเมต ผู้ช่วย AI ของคุณ ฉันจะพาคุณผ่านทุกขั้นตอนการจอง ตั้งแต่พรีเซลแฟนคลับจนถึงการชำระเงิน เพื่อให้คุณได้ที่นั่งที่ต้องการโดยไม่ตื่นตระหนก",
    introBullet1: "กลยุทธ์คิวแบบเรียลไทม์", introBullet2: "กรอกฟอร์มและยืนยันตัวตนอัตโนมัติ", introBullet3: "แนะนำที่นั่งอัจฉริยะ",
    introCta: "เริ่มจองตั๋ว", introNote: "เดโม · ไม่มีการชำระเงินจริง",
    s1: "คอนเสิร์ต", s2: "บัญชี", s3: "แฟนคลับ", s4: "คิว", s5: "ที่นั่ง", s6: "ชำระเงิน",
    s1Eyebrow: "ขั้นที่ 1 — เลือกคอนเสิร์ต", s1Title: "วันนี้เราจะคว้าคอนเสิร์ตไหนดี?", s1Sub: "เลือกคอนเสิร์ตที่ต้องการ แล้วฉันจะเตรียมทุกอย่างให้รอบนั้น",
    s1Ai: "เริ่มจากคอนเสิร์ตก่อน แตะคอนเสิร์ตที่ต้องการ แล้วฉันจะจัดพรีเซลและเวลาให้พอดี",
    hot: "ฮอต", from: "เริ่มต้น", select: "เลือก", selected: "เลือกแล้ว",
    s2a: "อีเมล", s2aSub: "เราจะส่งรหัสยืนยันมาที่นี่", s2b: "ยืนยัน", s2bSub: "กรอกรหัส 6 หลัก",
    s2c: "รหัสผ่าน", s2cSub: "ตั้งให้แข็งแรง — วันขายต้องเร็ว", s2d: "โปรไฟล์", s2dSub: "ชื่อจริงตามบัตรประชาชน (จำเป็นต่อการเข้างาน)",
    s2e: "โทรศัพท์", s2eSub: "สำหรับแจ้งเตือนวันขายและยืนยันตัวตน",
    emailPh: "you@email.com", codePh: "0 0 0 0 0 0", pwPh: "8 ตัวขึ้นไป", namePh: "ชื่อ-นามสกุล", phonePh: "+66 80 000 0000",
    resend: "ส่งรหัสอีกครั้ง", autofill: "เมตกรอกให้แล้ว", verified: "ยืนยันแล้ว", accountReady: "บัญชียืนยันแล้ว พร้อมใช้งาน",
    s3Eyebrow: "ขั้นที่ 3 — แฟนคลับ", s3Title: "สมัครแฟนคลับเพื่อสิทธิ์พรีเซล", s3Sub: "สมาชิกเข้าพรีเซลก่อน 48 ชม. — ที่นั่งดี ๆ หมดตรงนั้น",
    s3Ai: "เคล็ดลับ: ที่นั่งดีที่สุดขายในพรีเซล การสมัครแฟนคลับอย่างเป็นทางการปลดล็อกมัน ฉันแนะนำสมาชิกด้านล่าง",
    s3Benefit1: "เข้าพรีเซลก่อน 48 ชั่วโมง", s3Benefit2: "โซนที่นั่งเฉพาะสมาชิก", s3Benefit3: "หมายเลขคิวเฉลี่ยต่ำกว่า", s3Benefit4: "บัตรสมาชิกและสิทธิพิเศษ",
    membership: "สมาชิกอย่างเป็นทางการ", perYear: "/ ปี", joinNow: "สมัครและเปิดพรีเซล", joined: "สมาชิกใช้งานอยู่", memberNo: "เลขสมาชิก",
    s4Eyebrow: "ขั้นที่ 4 — ห้องรอคิว", s4Title: "คุณอยู่ในคิวแล้ว", s4Sub: "อยู่หน้านี้ไว้ รีเฟรชหรือออกจะถูกส่งไปท้ายแถว",
    s4Ai: "เปิดขายแล้วและคุณอยู่ในคิว อย่ารีเฟรชเด็ดขาด — ฉันรักษาที่ไว้ให้และจะบอกเมื่อถึงคิวคุณ",
    queuePosition: "ตำแหน่งของคุณ", peopleAhead: "คนอยู่ข้างหน้าคุณ", estWait: "เวลารอโดยประมาณ", queueTip: "เมตกำลังรักษาที่ให้ — รอสักครู่",
    yourTurn: "ถึงคิวคุณแล้ว!", yourTurnSub: "เข้ามาแล้ว ไปคว้าที่นั่งกัน — เร็ว ๆ", enterSeats: "เลือกที่นั่งเลย", min: "นาที", sec: "วินาที",
    s5Eyebrow: "ขั้นที่ 5 — เลือกที่นั่ง", s5Title: "เลือกที่นั่งของคุณ", s5Sub: "แตะที่นั่งว่าง ฉันไฮไลต์ที่คุ้มค่าและวิวดีไว้แล้ว",
    s5Ai: "เข้ามาแล้ว! ฉันสแกนผังที่นั่ง — ที่นั่งสีฟ้าคือสมดุลราคากับวิวที่ดีที่สุด รีบคว้าก่อนหมด",
    stage: "เวที", available: "ว่าง", taken: "เต็ม", yourPick: "ที่คุณเลือก", recommend: "เมตแนะนำ",
    seatsSelected: "ที่นั่งที่เลือก", selectSeatsHint: "เลือกได้สูงสุด 2 ที่นั่ง", seatSummary: "ที่นั่งที่เลือก", subtotal: "ยอดรวมย่อย", toPayment: "ไปชำระเงิน",
    s6Eyebrow: "ขั้นที่ 6 — ชำระเงิน", s6Title: "ขั้นสุดท้าย — ชำระเงิน", s6Sub: "ที่นั่งถูกจองไว้ 7:00 นาที ชำระเงินให้เสร็จเพื่อยืนยัน",
    s6Ai: "ที่นั่งถูกจองไว้แค่ 7 นาที มาชำระเงินให้เสร็จก่อนหมดเวลา — ฉันกรอกข้อมูลให้แล้ว",
    held: "จองที่นั่งไว้แล้ว", orderSummary: "สรุปคำสั่งซื้อ", bookingFee: "ค่าธรรมเนียมจอง", total: "รวมทั้งหมด",
    payMethod: "วิธีชำระเงิน", card: "บัตร", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "หมายเลขบัตร", cardPh: "1234 5678 9012 3456", expiry: "วันหมดอายุ", expPh: "ดด/ปป", cvc: "CVC", cvcPh: "•••",
    agree: "ฉันยอมรับเงื่อนไขและนโยบายไม่คืนเงิน", payNow: "ชำระเงิน", processing: "กำลังจองที่นั่งให้คุณ…",
    doneEyebrow: "ยืนยันการจองแล้ว", doneTitle: "ได้ตั๋วแล้ว! 🎉", doneSub: "เมตพาคุณผ่าน 6 ขั้นตอนในเวลาสุดเร็ว ตั๋วอิเล็กทรอนิกส์พร้อมแล้ว",
    doneAi: "เราทำได้! ได้ตั๋วแล้ว ฉันส่งอีตั๋วไปที่อีเมลและเพิ่มงานลงปฏิทินให้แล้ว ขอให้สนุกกับคอนเสิร์ต!",
    bookingNo: "หมายเลขการจอง", eTicket: "อีตั๋ว", seatLabel: "ที่นั่ง", addCalendar: "เพิ่มลงปฏิทิน",
    viewTickets: "ดูอีตั๋ว", bookAnother: "จองงานอื่น", timeTaken: "เวลารวมกับเมต", admitOne: "เข้างาน",
    s2Title: "ก่อนจอง มาตรวจสอบความพร้อมของบัญชีกันก่อน",
    s2Sub: "4 เรื่องที่แฟน ๆ ต่างชาติติดบ่อยที่สุด — จัดการตอนนี้เพื่อเลี่ยงการถูกปฏิเสธตอนรับตั๋วและการชำระเงินล้มเหลว",
    s2Ai: "จริง ๆ แล้วสงครามตั๋วครึ่งหนึ่งแพ้ตั้งแต่ก่อนเปิดขาย การสะกดชื่อข้ามแพลตฟอร์ม วันหมดอายุพาสปอร์ต การจ่ายด้วยบัตรต่างประเทศ และการแจ้งเตือนเวลาเปิด — มาตรวจทั้งสี่อย่างตอนนี้กัน",
  };

  const ID = {
    code: "ID", appTag: "Kopilot tiket bertenaga AI", aiName: "Mate", aiStatus: "online · memandu kamu",
    next: "Lanjut", back: "Kembali", confirm: "Konfirmasi", step: "Langkah", of: "dari",
    introEyebrow: "Selamat datang di TickeMate AI", introTitle: "Tak akan kalah lagi dalam perang tiket.",
    introSub: "Aku Mate, kopilot AI-mu. Aku akan memandu setiap langkah pembelian, dari presale fan club sampai pembayaran, agar kamu dapat kursi impian tanpa panik.",
    introBullet1: "Strategi antrean real-time", introBullet2: "Formulir & verifikasi otomatis", introBullet3: "Rekomendasi kursi cerdas",
    introCta: "Mulai pesan", introNote: "Demo · tidak ada pembayaran nyata",
    s1: "Konser", s2: "Akun", s3: "Fan Club", s4: "Antrean", s5: "Kursi", s6: "Bayar",
    s1Eyebrow: "Langkah 1 — Pilih konser", s1Title: "Konser mana yang kita menangkan hari ini?", s1Sub: "Pilih konser yang kamu incar. Aku siapkan semuanya untuk penjualan itu.",
    s1Ai: "Mulai dari konsernya. Ketuk konser yang kamu mau, aku atur presale dan waktunya.",
    hot: "POPULER", from: "mulai", select: "Pilih", selected: "Dipilih",
    s2a: "Email", s2aSub: "Kami kirim kode verifikasi ke sini", s2b: "Verifikasi", s2bSub: "Masukkan kode 6 digit",
    s2c: "Kata sandi", s2cSub: "Buat yang kuat — hari-H harus cepat", s2d: "Profil", s2dSub: "Nama asli sesuai identitas (wajib untuk masuk)",
    s2e: "Telepon", s2eSub: "Untuk notifikasi hari-H & verifikasi",
    emailPh: "kamu@email.com", codePh: "0 0 0 0 0 0", pwPh: "8+ karakter", namePh: "Nama lengkap", phonePh: "+62 812 0000 0000",
    resend: "Kirim ulang kode", autofill: "Mate mengisi ini", verified: "Terverifikasi", accountReady: "Akun terverifikasi & siap",
    s3Eyebrow: "Langkah 3 — Fan Club", s3Title: "Gabung fan club untuk akses presale", s3Sub: "Member masuk 48 jam lebih awal — di situ kursi terbaik habis.",
    s3Ai: "Rahasianya: kursi terbaik terjual di presale. Gabung fan club resmi membukanya. Aku sarankan keanggotaan di bawah.",
    s3Benefit1: "Akses presale 48 jam lebih awal", s3Benefit2: "Blok kursi khusus member", s3Benefit3: "Nomor antrean rata-rata lebih kecil", s3Benefit4: "Kartu member & keuntungan eksklusif",
    membership: "KEANGGOTAAN RESMI", perYear: "/ tahun", joinNow: "Gabung & buka presale", joined: "Keanggotaan aktif", memberNo: "No. member",
    s4Eyebrow: "Langkah 4 — Ruang tunggu", s4Title: "Kamu ada di antrean", s4Sub: "Tetap di halaman ini. Refresh atau keluar bikin kamu ke belakang.",
    s4Ai: "Penjualan dibuka dan kamu di antrean. JANGAN refresh — aku jaga tempatmu dan beri tahu saat giliranmu.",
    queuePosition: "Posisimu", peopleAhead: "orang di depanmu", estWait: "Perkiraan tunggu", queueTip: "Mate menjaga tempatmu — sabar ya.",
    yourTurn: "Giliranmu!", yourTurnSub: "Kamu masuk. Ayo ambil kursinya — cepat.", enterSeats: "Pilih kursi sekarang", min: "mnt", sec: "dtk",
    s5Eyebrow: "Langkah 5 — Pilih kursi", s5Title: "Pilih kursimu", s5Sub: "Ketuk kursi yang tersedia. Aku tandai yang terbaik dari segi harga & pandangan.",
    s5Ai: "Kita masuk! Aku pindai peta — kursi biru adalah keseimbangan terbaik harga & pandangan. Ambil sebelum habis.",
    stage: "PANGGUNG", available: "Tersedia", taken: "Terisi", yourPick: "Pilihanmu", recommend: "Pilihan Mate",
    seatsSelected: "kursi dipilih", selectSeatsHint: "Pilih maksimal 2 kursi", seatSummary: "Kursi terpilih", subtotal: "Subtotal", toPayment: "Ke pembayaran",
    s6Eyebrow: "Langkah 6 — Pembayaran", s6Title: "Langkah terakhir — bayar", s6Sub: "Kursimu ditahan 7:00. Selesaikan pembayaran untuk menguncinya.",
    s6Ai: "Kursi sudah dipesan tapi cuma 7 menit. Ayo selesaikan pembayaran sebelum waktu habis — datamu sudah kuisi.",
    held: "Kursi ditahan", orderSummary: "Ringkasan pesanan", bookingFee: "Biaya pemesanan", total: "Total",
    payMethod: "Metode pembayaran", card: "Kartu", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "Nomor kartu", cardPh: "1234 5678 9012 3456", expiry: "Kedaluwarsa", expPh: "BB/TT", cvc: "CVC", cvcPh: "•••",
    agree: "Saya setuju dengan syarat tiket & kebijakan tanpa pengembalian", payNow: "Bayar", processing: "Mengamankan kursimu…",
    doneEyebrow: "Pemesanan dikonfirmasi", doneTitle: "Kamu dapat tiketnya! 🎉", doneSub: "Mate memandumu lewat 6 langkah dengan rekor waktu. E-tiketmu siap.",
    doneAi: "Berhasil! Tiket aman. Aku kirim e-tiket ke emailmu dan tambahkan konser ke kalender. Selamat menikmati konser!",
    bookingNo: "Nomor pemesanan", eTicket: "E-TIKET", seatLabel: "Kursi", addCalendar: "Tambah ke kalender",
    viewTickets: "Lihat e-tiket", bookAnother: "Pesan konser lain", timeTaken: "Total waktu dengan Mate", admitOne: "MASUK",
    s2Title: "Sebelum pesan, cek dulu kesiapan akunmu",
    s2Sub: "Empat hal yang paling sering menghambat fan internasional — diselesaikan sekarang agar tak ditolak saat ambil tiket dan pembayaran gagal.",
    s2Ai: "Jujur, separuh perang tiket kalah sebelum penjualan dibuka. Ejaan nama antar platform, masa berlaku paspor, pembayaran kartu luar negeri, dan alarm pembukaan — ayo cek keempatnya sekarang.",
  };

  const TL = {
    code: "TL", appTag: "AI ticketing co-pilot", aiName: "Mate", aiStatus: "online · ginagabayan ka",
    next: "Magpatuloy", back: "Bumalik", confirm: "Kumpirmahin", step: "Hakbang", of: "ng",
    introEyebrow: "Maligayang pagdating sa TickeMate AI", introTitle: "Hindi ka na matatalo sa ticket war.",
    introSub: "Ako si Mate, ang AI co-pilot mo. Gagabayan kita sa bawat hakbang ng booking, mula presale ng fan club hanggang bayad, para makuha mo ang gustong upuan nang walang panic.",
    introBullet1: "Real-time na estratehiya sa pila", introBullet2: "Awtomatikong form at beripikasyon", introBullet3: "Matalinong rekomendasyon ng upuan",
    introCta: "Simulan ang booking", introNote: "Demo · walang totoong bayad na pinoproseso",
    s1: "Konsiyerto", s2: "Account", s3: "Fan Club", s4: "Pila", s5: "Upuan", s6: "Bayad",
    s1Eyebrow: "Hakbang 1 — Piliin ang show", s1Title: "Aling konsiyerto ang pananalunin natin ngayon?", s1Sub: "Piliin ang show na gusto mo. Ihahanda ko ang lahat para doon.",
    s1Ai: "Magsimula tayo sa show. I-tap ang konsiyertong gusto mo, ihahanda ko ang presale at timing.",
    hot: "SIKAT", from: "mula", select: "Piliin", selected: "Napili",
    s2a: "Email", s2aSub: "Magpapadala kami ng verification code dito", s2b: "I-verify", s2bSub: "Ilagay ang 6-digit na code",
    s2c: "Password", s2cSub: "Gawing matibay — bilisan sa araw ng benta", s2d: "Profile", s2dSub: "Tunay na pangalan gaya sa ID (kailangan para makapasok)",
    s2e: "Telepono", s2eSub: "Para sa alerto sa araw ng benta at beripikasyon",
    emailPh: "ikaw@email.com", codePh: "0 0 0 0 0 0", pwPh: "8+ na karakter", namePh: "Buong pangalan", phonePh: "+63 917 000 0000",
    resend: "Ipadala muli ang code", autofill: "Pinunan ito ni Mate", verified: "Na-verify", accountReady: "Na-verify ang account at handa na",
    s3Eyebrow: "Hakbang 3 — Fan Club", s3Title: "Sumali sa fan club para sa presale", s3Sub: "Mga miyembro ay nakakapasok 48 oras nang maaga — doon nauubos ang pinakamagandang upuan.",
    s3Ai: "Sikreto: ang pinakamagandang upuan ay nabebenta sa presale. Ang pagsali sa opisyal na fan club ang nagbubukas nito. Inirerekomenda ko ang membership sa ibaba.",
    s3Benefit1: "Presale access 48 oras nang maaga", s3Benefit2: "Bloke ng upuan para sa miyembro lang", s3Benefit3: "Mas mababang numero sa pila sa karaniwan", s3Benefit4: "Eksklusibong membership card at perks",
    membership: "OPISYAL NA MEMBERSHIP", perYear: "/ taon", joinNow: "Sumali at buksan ang presale", joined: "Aktibo ang membership", memberNo: "Member No.",
    s4Eyebrow: "Hakbang 4 — Waiting room", s4Title: "Nasa pila ka na", s4Sub: "Manatili sa page na ito. Ang pag-refresh o pag-alis ay magpapadala sa iyo sa dulo.",
    s4Ai: "Live na ang benta at nasa pila ka. HUWAG mag-refresh — iniingatan ko ang puwesto mo at sasabihin ko kapag turn mo na.",
    queuePosition: "Posisyon mo", peopleAhead: "tao ang nauna sa iyo", estWait: "Tinatayang hintay", queueTip: "Iniingatan ni Mate ang puwesto mo — sandali lang.",
    yourTurn: "Turn mo na!", yourTurnSub: "Pasok ka na. Kunin natin ang upuan — bilis.", enterSeats: "Pumili ng upuan ngayon", min: "min", sec: "seg",
    s5Eyebrow: "Hakbang 5 — Pagpili ng upuan", s5Title: "Piliin ang upuan mo", s5Sub: "I-tap ang bakanteng upuan. Hinighlight ko ang sulit na may magandang tanaw.",
    s5Ai: "Pasok na tayo! Ini-scan ko ang mapa — ang asul na upuan ang pinakamagandang balanse ng presyo at tanaw. Kunin bago maubos.",
    stage: "ENTABLADO", available: "Bakante", taken: "Kuha na", yourPick: "Pinili mo", recommend: "Pili ni Mate",
    seatsSelected: "upuan ang napili", selectSeatsHint: "Pumili ng hanggang 2 upuan", seatSummary: "Mga napiling upuan", subtotal: "Subtotal", toPayment: "Pumunta sa bayad",
    s6Eyebrow: "Hakbang 6 — Bayad", s6Title: "Huling hakbang — bayad", s6Sub: "Nakareserba ang upuan mo sa 7:00. Kumpletuhin ang bayad para ma-lock.",
    s6Ai: "Nakareserba ang upuan pero 7 minuto lang. Tapusin natin ang bayad bago maubos ang oras — pinunan ko na ang detalye mo.",
    held: "Nakareserba ang upuan", orderSummary: "Buod ng order", bookingFee: "Booking fee", total: "Kabuuan",
    payMethod: "Paraan ng bayad", card: "Card", kakao: "KakaoPay", naver: "NaverPay",
    cardNo: "Numero ng card", cardPh: "1234 5678 9012 3456", expiry: "Petsa ng expiry", expPh: "MM/YY", cvc: "CVC", cvcPh: "•••",
    agree: "Sumasang-ayon ako sa mga tuntunin at no-refund na patakaran", payNow: "Magbayad", processing: "Sinisiguro ang upuan mo…",
    doneEyebrow: "Nakumpirma ang booking", doneTitle: "Nakuha mo ang tiket! 🎉", doneSub: "Ginabayan ka ni Mate sa 6 na hakbang sa record time. Handa na ang e-tickets mo.",
    doneAi: "Nagawa natin! Sigurado na ang tiket. Pinadala ko ang e-tickets sa email mo at idinagdag ang show sa kalendaryo. Enjoy sa konsiyerto!",
    bookingNo: "Numero ng booking", eTicket: "E-TICKET", seatLabel: "Upuan", addCalendar: "Idagdag sa kalendaryo",
    viewTickets: "Tingnan ang e-tickets", bookAnother: "Mag-book ng iba", timeTaken: "Kabuuang oras kay Mate", admitOne: "PAGPASOK",
    s2Title: "Bago mag-book, tingnan muna kung handa ang account mo",
    s2Sub: "Apat na bagay na madalas ikasagabal ng international fans — aayusin ngayon para maiwasan ang pagtanggi sa pickup at bigong bayad.",
    s2Ai: "Sa totoo lang, kalahati ng ticket war ay natatalo bago pa magbukas ang benta. Spelling ng pangalan sa iba't ibang platform, validity ng pasaporte, bayad gamit foreign card, at alerto sa pagbukas — tingnan natin ang apat ngayon.",
  };

  const extra = { es: ES, pt: PT, fr: FR, th: TH, id: ID, tl: TL };
  // Merge with English as the base so any missing key (incl. the detailed
  // Step-2 `s2x` module) gracefully falls back to English instead of blank.
  Object.keys(extra).forEach((k) => {
    T[k] = Object.assign({}, T.en, extra[k]);
    T[k].s2x = T.en.s2x;
  });
})();
